### ISSUE TITLE
What/where is "analysis_predictor.cc"? - Deprecation in python 3.10.9

### ISSUE THREAD

**Issue by Jimw338** [Destaq/chinese-comprehension#6] opened 2023-02-22 23:05 UTC
What is "analysis_predictor.cc"?  Is it somewhere in the LAC library (I didn't see it).  My Python environment, which is 3.10.9, running inside a conda environment for running on macOS M1 *.  When I run this, I get c deprecated error for analysis_predictor.cc at line 2166.  What is this?

(*) Using instructions from here [https://www.benmather.info/post/2022-07-07-python-for-mac-m1/]

**Comment by Destaq** [comment] 2023-02-22 23:15
`analysis_predictor.cc` is not part of this package - please read through the stack trace or do a Google search to see which one it does belong to.

Is my tool still able to work on your machine? If so, this is a downstream problem, and not something that warrants an issue in the repo.

**Comment by Destaq** [comment] 2023-02-24 12:13
Since you've confirmed that this [isn't due to `chinese-comprehension`](https://github.com/PaddlePaddle/PaddleOCR/issues/1550#issuecomment-1442100025) (please comment here with that as well next time!), I'm closing the issue.

**Closed as completed by Destaq** 2023-02-24 12:13 UTC
Labels: invalid
